version: "3"

services:
  wechatbot:
    build: .
    container_name: wechatbot
    restart: always
    ports:
      - "8001:8001"
    #volumes:
    #  - .:/app
    depends_on:
      - redis
      
  redis:
    image: "redis:6.0.10-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
