version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=test1.mcxiaoke.com
      - NGINX_PORT=80
      - NGINX_SSL_PORT=443
      - NGINX_PROXY_PASS=http://127.0.0.1:8000

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  wechat-robot:
    container_name: wechat-robot
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - nginx
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    #volumes:
    #  - ../src:/opt/wechat-robot
